"""Endpoint routers grouped for version 1 of the API."""

from . import (
    auth,
    company_product_prices,
    reports,
    users,
    roles,
    permissions,
    produtores,
    produtos,
    firmas,
    cargas,
    veiculos,
    fretes,
    embalagens,
    coletas,
    freight_rates,
    services,
    tipos_manutencao,
    manutencoes,
    package_deliveries,
    package_stock,
)

__all__ = [
    "auth",
    "company_product_prices",
    "reports",
    "users",
    "roles",
    "permissions",
    "produtores",
    "produtos",
    "firmas",
    "cargas",
    "veiculos",
    "fretes",
    "embalagens",
    "coletas",
    "freight_rates",
    "services",
    "tipos_manutencao",
    "manutencoes",
    "package_deliveries",
    "package_stock",
]
